javac^
 main\logic\com\teamalfa\blindvirologists\agents\genetic_code\*.java^
 main\logic\com\teamalfa\blindvirologists\agents\virus\*.java^
 main\logic\com\teamalfa\blindvirologists\agents\*.java^
 main\logic\com\teamalfa\blindvirologists\city\fields\*.java^
 main\logic\com\teamalfa\blindvirologists\city\*.java^
 main\logic\com\teamalfa\blindvirologists\consoleController\*.java^
 main\logic\com\teamalfa\blindvirologists\equipments\active_equipments\*.java^
 main\logic\com\teamalfa\blindvirologists\equipments\*.java^
 main\logic\com\teamalfa\blindvirologists\random\*.java^
 main\logic\com\teamalfa\blindvirologists\turn_handler\*.java^
 main\logic\com\teamalfa\blindvirologists\virologist\backpack\pockets\*.java^
 main\logic\com\teamalfa\blindvirologists\virologist\backpack\*.java^
 main\logic\com\teamalfa\blindvirologists\virologist\*.java^
 main\logic\com\teamalfa\blindvirologists\*.java^
 main\GUI\view\buttons\*.java^
 main\GUI\view\frames\menuFrames\*.java^
 main\GUI\view\frames\*.java^
 main\GUI\view\labels\*.java^
 main\GUI\view\menus\*.java^
 main\GUI\view\panels\*.java^
 main\GUI\view\view\agentView\*.java^
 main\GUI\view\view\equipmentView\*.java^
 main\GUI\view\view\fieldView\*.java^
 main\GUI\view\view\geneticCodeView\*.java^
 main\GUI\view\view\*.java